# NumPy Basics
## Task 1

Make sure that NumPy is imported to your IPython shell

In [2]:
import numpy as np

a) Generate an arbitrary one dimensional array `n` with `n.shape=(8,)` and display it.

In [10]:
n = np.array([3,8,12,18,7,11,30])
print(n)

[ 3  8 12 18  7 11 30]


b) Create a new array `n_odd` which consists of the odd entries of `n`. Display it.

In [11]:
n_odd = n[1::2]
print(n_odd)

[ 8 18 11]


In [13]:
n % 2 == 1

array([ True, False, False, False,  True,  True, False])

c) Create a new array `n_rev` which contains the entries of `n` in reverse order. Display it.

In [4]:
n_rev = n[::-1]
print(n_rev)

[30 11  7 18 12  8  3]


d) What would be the output of the following code?

In [14]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
print(a[1])
a

200


array([  1, 200,   3,   4,   5])

e) Create a two-dimensional array called `m` with `m.shape=(3,4)` and display it.

In [16]:
m = np.array(
    [
        [11, 12, 13, 14], 
        [21, 22, 23, 24], 
        [31, 32, 33, 34]
    ]
)
print(m)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Create another array `m_revrowel` which contains the same elements as `m`, but with reversed rows. Display it.

In [7]:
m_revrowel = m[:, ::-1]
print(m_revrowel)

[[14 13 12 11]
 [24 23 22 21]
 [34 33 32 31]]


Create yet another array `m_revall` which contains the same elements as `m`, but with reversed rows and columns. Display it.

In [8]:
m_revall = m[::-1, ::-1]
print(m_revall)

[[34 33 32 31]
 [24 23 22 21]
 [14 13 12 11]]


Create an array `m_cut` which contains only the elements from the first and last rows and columns of `m`. Display it.

In [20]:
m_cut_temp = m[(0,-1),:]
m_cut = m_cut_temp[:,(0,-1)]
print(m_cut)

[[11 14]
 [31 34]]


In [22]:
m[[[0], [-1]], [0, -1]]

array([[11, 14],
       [31, 34]])